apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:devteam-red, applications, get, project-red/*, allow
    p, role:devteam-red, applications, create, project-red/*, allow
    p, role:devteam-red, applications, update, project-red/*, allow
    p, role:devteam-red, applications, delete, project-red/*, allow
    p, role:devteam-red, applications, sync, project-red/*, allow
    g, bobsacamano, role:devteam-red